name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Or your Ruby version
          bundler-cache: true

      - uses: actions/configure-pages@v2
      - run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

#      - name: Verify _site directory
#        run: ls -al _site

      - name: Verify _site directory contents
        run: |
        if [ -d "./_site" ]; then
          echo "_site directory exists"
          ls -al ./_site
        else
          echo "_site directory does not exist"
          exit 1
        fi

      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages # This name is important, but not directly used by deploy-pages@v2
          path: './_site'   # This path is crucial - it packages the _site directory

#      - name: Get artifact URL
#        if: always()
#           run: echo "Artifact URL: ${{ steps.upload_artifact.outputs.url }}"

      - uses: actions/deploy-pages@v2  # This action automatically finds the artifact from the same workflow run
